services:
  # Base de Datos Local
  db:
    image: postgres:15-alpine
    container_name: iter_postgres
    restart: always
    env_file:
      - apps/api/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-iter_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iter-network

  # Adminer (Visualizador DB)
  adminer:
    image: adminer
    container_name: iter_adminer
    restart: always
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    networks:
      - iter-network

  # Service de Instalación y Setup
  setup:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    working_dir: /app
    volumes:
      - .:/app
      - node_modules_cache:/app/node_modules
    command: sh -c "npm install && npx turbo db:generate --filter=api && npx prisma db push --force-reset --schema=apps/api/prisma/schema.prisma && npx turbo db:seed --filter=api"
    env_file:
      - apps/api/.env
    depends_on:
      - db
    networks:
      - iter-network

  # Backend API (Dev)
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    working_dir: /app
    command: npx turbo dev --filter=api
    volumes:
      - .:/app
      - node_modules_cache:/app/node_modules
    ports:
      - "${API_PORT:-3000}:${PORT:-3000}"
    env_file:
      - apps/api/.env
    depends_on:
      setup:
        condition: service_completed_successfully
    networks:
      - iter-network

  # Frontend Web (Dev)
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    working_dir: /app
    command: npx turbo dev --filter=web
    volumes:
      - .:/app
      - node_modules_cache:/app/node_modules
    ports:
      - "${WEB_PORT:-8002}:${PORT:-3001}"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - apps/web/.env
    depends_on:
      setup:
        condition: service_completed_successfully
    networks:
      - iter-network

networks:
  iter-network:
    driver: bridge

volumes:
  postgres_data:
  node_modules_cache:
