var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/centros/page.js")
R.c("server/chunks/ssr/Documents_Code_Projects_iter-ecosystem-enginy_2bee8a94._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7dd48f70._.js")
R.c("server/chunks/ssr/Documents_Code_Projects_iter-ecosystem-enginy_87852cad._.js")
R.c("server/chunks/ssr/[root-of-the-server]__692d7ab4._.js")
R.c("server/chunks/ssr/2d0c9_next_dist_b5d6eb37._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6387ae91._.js")
R.c("server/chunks/ssr/2d0c9_next_dist_client_components_builtin_global-error_e5ea971d.js")
R.c("server/chunks/ssr/[root-of-the-server]__c4ea139d._.js")
R.c("server/chunks/ssr/2d0c9_next_dist_client_components_75d464de._.js")
R.c("server/chunks/ssr/2d0c9_next_dist_client_components_builtin_forbidden_400009a8.js")
R.c("server/chunks/ssr/2d0c9_next_dist_client_components_builtin_unauthorized_5c70cae6.js")
R.c("server/chunks/ssr/6a429_apps_web__next-internal_server_app_admin_centros_page_actions_42ad2848.js")
R.m(88165)
module.exports=R.m(88165).exports
